//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeDi.Server2.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MatchAdd {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MatchAdd() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeDi.Server2.Resources.Pages.MatchAdd", typeof(MatchAdd).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend match in case of draw after regular play time.
        /// </summary>
        public static string ExtendMatch {
            get {
                return ResourceManager.GetString("ExtendMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handball.
        /// </summary>
        public static string Handball {
            get {
                return ResourceManager.GetString("Handball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of a period (minutes : seconds).
        /// </summary>
        public static string LengthPeriod {
            get {
                return ResourceManager.GetString("LengthPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data....
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match pauses in case of interruptions near end of match.
        /// </summary>
        public static string MatchInterruptions {
            get {
                return ResourceManager.GetString("MatchInterruptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match has overtime.
        /// </summary>
        public static string MatchOvertime {
            get {
                return ResourceManager.GetString("MatchOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New match.
        /// </summary>
        public static string NewMatch {
            get {
                return ResourceManager.GetString("NewMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of seconds near end the time will be stopped?.
        /// </summary>
        public static string NumberOfSeconds {
            get {
                return ResourceManager.GetString("NumberOfSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of periods.
        /// </summary>
        public static string NumberPeriods {
            get {
                return ResourceManager.GetString("NumberPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on display:.
        /// </summary>
        public static string OnDisplay {
            get {
                return ResourceManager.GetString("OnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Start.
        /// </summary>
        public static string SaveStart {
            get {
                return ResourceManager.GetString("SaveStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Start Date and Time.
        /// </summary>
        public static string ScheduledDateTime {
            get {
                return ResourceManager.GetString("ScheduledDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sport.
        /// </summary>
        public static string SelectSport {
            get {
                return ResourceManager.GetString("SelectSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soccer.
        /// </summary>
        public static string Soccer {
            get {
                return ResourceManager.GetString("Soccer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team 1 name.
        /// </summary>
        public static string Team1 {
            get {
                return ResourceManager.GetString("Team1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team 2 name.
        /// </summary>
        public static string Team2 {
            get {
                return ResourceManager.GetString("Team2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underwaterhockey.
        /// </summary>
        public static string Underwaterhockey {
            get {
                return ResourceManager.GetString("Underwaterhockey", resourceCulture);
            }
        }
    }
}
