//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeDi.Server2.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MatchControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MatchControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeDi.Server2.Resources.Pages.MatchControl", typeof(MatchControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Match.
        /// </summary>
        public static string CancelMatch {
            get {
                return ResourceManager.GetString("CancelMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close match.
        /// </summary>
        public static string CloseMatch {
            get {
                return ResourceManager.GetString("CloseMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hide advanced controls.
        /// </summary>
        public static string HideControls {
            get {
                return ResourceManager.GetString("HideControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend: Green = Running Match, Gray = Finished Match, Blue = Ready to Start, Other = White.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Match....
        /// </summary>
        public static string LoadingMatch {
            get {
                return ResourceManager.GetString("LoadingMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Matches....
        /// </summary>
        public static string LoadingMatches {
            get {
                return ResourceManager.GetString("LoadingMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Penalty.
        /// </summary>
        public static string LogPenalty {
            get {
                return ResourceManager.GetString("LogPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match ended.
        /// </summary>
        public static string MatchEnded {
            get {
                return ResourceManager.GetString("MatchEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set match time left.
        /// </summary>
        public static string MatchTimeLeft {
            get {
                return ResourceManager.GetString("MatchTimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently no matches running..
        /// </summary>
        public static string NoMatchesOngoing {
            get {
                return ResourceManager.GetString("NoMatchesOngoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match events available..
        /// </summary>
        public static string NoMatchEventsAvailable_ {
            get {
                return ResourceManager.GetString("NoMatchEventsAvailable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the permission to view this page..
        /// </summary>
        public static string NoPermissions {
            get {
                return ResourceManager.GetString("NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not loggged in..
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referee Match.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select penalty to revoke.
        /// </summary>
        public static string PenaltyRevoke {
            get {
                return ResourceManager.GetString("PenaltyRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to perfom that action?.
        /// </summary>
        public static string PerfomThatAction {
            get {
                return ResourceManager.GetString("PerfomThatAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period:.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare next period.
        /// </summary>
        public static string PrepareNextPeriod {
            get {
                return ResourceManager.GetString("PrepareNextPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Match.
        /// </summary>
        public static string RestartMatch {
            get {
                return ResourceManager.GetString("RestartMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke Penalty.
        /// </summary>
        public static string RevokePenalty {
            get {
                return ResourceManager.GetString("RevokePenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke Score.
        /// </summary>
        public static string RevokeScore {
            get {
                return ResourceManager.GetString("RevokeScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device.
        /// </summary>
        public static string SelectDevice {
            get {
                return ResourceManager.GetString("SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the penalty.
        /// </summary>
        public static string SelectPenalty {
            get {
                return ResourceManager.GetString("SelectPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the penalty for the selected player..
        /// </summary>
        public static string SelectPenaltyPlayer_ {
            get {
                return ResourceManager.GetString("SelectPenaltyPlayer.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select playernumber.
        /// </summary>
        public static string SelectPlayernumber {
            get {
                return ResourceManager.GetString("SelectPlayernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select playernumber the penalty applies to.
        /// </summary>
        public static string SelectPlayernumberAppliesTo {
            get {
                return ResourceManager.GetString("SelectPlayernumberAppliesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set match time.
        /// </summary>
        public static string SetMatchTime {
            get {
                return ResourceManager.GetString("SetMatchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the time to the time left for the current match. Pause the match to stop the time from keep running before setting the time..
        /// </summary>
        public static string SetMatchTimeLeft {
            get {
                return ResourceManager.GetString("SetMatchTimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Show advanced controls.
        /// </summary>
        public static string ShowControls {
            get {
                return ResourceManager.GetString("ShowControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on display.
        /// </summary>
        public static string ShowOnDisplay {
            get {
                return ResourceManager.GetString("ShowOnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Continue.
        /// </summary>
        public static string Start_Continue {
            get {
                return ResourceManager.GetString("Start/Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Match or Matches....
        /// </summary>
        public static string UnableToLoadMatch {
            get {
                return ResourceManager.GetString("UnableToLoadMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vs..
        /// </summary>
        public static string vs {
            get {
                return ResourceManager.GetString("vs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the device the match should be shown at..
        /// </summary>
        public static string WhichDevice {
            get {
                return ResourceManager.GetString("WhichDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which penalty should be revoked?.
        /// </summary>
        public static string WhichPenaltyRevoke {
            get {
                return ResourceManager.GetString("WhichPenaltyRevoke", resourceCulture);
            }
        }
    }
}
