//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeDi.WebClient.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MatchControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MatchControl() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeDi.WebClient.Resources.Pages.MatchControl", typeof(MatchControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Canceled ähnelt.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel Match ähnelt.
        /// </summary>
        public static string CancelMatch {
            get {
                return ResourceManager.GetString("CancelMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close match ähnelt.
        /// </summary>
        public static string CloseMatch {
            get {
                return ResourceManager.GetString("CloseMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Hide advanced controls ähnelt.
        /// </summary>
        public static string HideControls {
            get {
                return ResourceManager.GetString("HideControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legend: Green = Running Match, Gray = Finished Match, Blue = Ready to Start, Other = White ähnelt.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Match... ähnelt.
        /// </summary>
        public static string LoadingMatch {
            get {
                return ResourceManager.GetString("LoadingMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading Matches... ähnelt.
        /// </summary>
        public static string LoadingMatches {
            get {
                return ResourceManager.GetString("LoadingMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log Penalty ähnelt.
        /// </summary>
        public static string LogPenalty {
            get {
                return ResourceManager.GetString("LogPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match ended ähnelt.
        /// </summary>
        public static string MatchEnded {
            get {
                return ResourceManager.GetString("MatchEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set match time left ähnelt.
        /// </summary>
        public static string MatchTimeLeft {
            get {
                return ResourceManager.GetString("MatchTimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No match events available. ähnelt.
        /// </summary>
        public static string NoMatchEventsAvailable_ {
            get {
                return ResourceManager.GetString("NoMatchEventsAvailable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Note ähnelt.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Referee Match ähnelt.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select penalty to revoke ähnelt.
        /// </summary>
        public static string PenaltyRevoke {
            get {
                return ResourceManager.GetString("PenaltyRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to perfom that action? ähnelt.
        /// </summary>
        public static string PerfomThatAction {
            get {
                return ResourceManager.GetString("PerfomThatAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Period: ähnelt.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prepare next period ähnelt.
        /// </summary>
        public static string PrepareNextPeriod {
            get {
                return ResourceManager.GetString("PrepareNextPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart Match ähnelt.
        /// </summary>
        public static string RestartMatch {
            get {
                return ResourceManager.GetString("RestartMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revoke Penalty ähnelt.
        /// </summary>
        public static string RevokePenalty {
            get {
                return ResourceManager.GetString("RevokePenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Revoke Score ähnelt.
        /// </summary>
        public static string RevokeScore {
            get {
                return ResourceManager.GetString("RevokeScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score ähnelt.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the penalty ähnelt.
        /// </summary>
        public static string SelectPenalty {
            get {
                return ResourceManager.GetString("SelectPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the penalty for the selected player. ähnelt.
        /// </summary>
        public static string SelectPenaltyPlayer_ {
            get {
                return ResourceManager.GetString("SelectPenaltyPlayer.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select playernumber ähnelt.
        /// </summary>
        public static string SelectPlayernumber {
            get {
                return ResourceManager.GetString("SelectPlayernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select playernumber the penalty applies to ähnelt.
        /// </summary>
        public static string SelectPlayernumberAppliesTo {
            get {
                return ResourceManager.GetString("SelectPlayernumberAppliesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set match time ähnelt.
        /// </summary>
        public static string SetMatchTime {
            get {
                return ResourceManager.GetString("SetMatchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set the time to the time left for the current match. Pause the match to stop the time from keep running before setting the time. ähnelt.
        /// </summary>
        public static string SetMatchTimeLeft {
            get {
                return ResourceManager.GetString("SetMatchTimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Show advanced controls ähnelt.
        /// </summary>
        public static string ShowControls {
            get {
                return ResourceManager.GetString("ShowControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show on display ähnelt.
        /// </summary>
        public static string ShowOnDisplay {
            get {
                return ResourceManager.GetString("ShowOnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start/Continue ähnelt.
        /// </summary>
        public static string Start_Continue {
            get {
                return ResourceManager.GetString("Start/Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to load Match or Matches... ähnelt.
        /// </summary>
        public static string UnableToLoadMatch {
            get {
                return ResourceManager.GetString("UnableToLoadMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die vs. ähnelt.
        /// </summary>
        public static string vs {
            get {
                return ResourceManager.GetString("vs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Which penalty should be revoked? ähnelt.
        /// </summary>
        public static string WhichPenaltyRevoke {
            get {
                return ResourceManager.GetString("WhichPenaltyRevoke", resourceCulture);
            }
        }
    }
}
